POST http://localhost:8081/permissions/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "read-permission",
  "description": "Grant access to create a permission"
}

###
GET http://localhost:8081/permissions/85d3a1a3-4544-4397-b7a8-b9d419715380
Authorization: Bearer {{authToken}}

###
POST http://localhost:8081/roles/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Admin1",
  "description": "Admin role"
}

###
GET http://localhost:8081/roles/5658b58d-b749-4a74-bb71-483324eb0705
Authorization: Bearer {{authToken}}

###
POST http://localhost:8081/roles/permissions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "roleId": "5658b58d-b749-4a74-bb71-483324eb0705",
  "permissionId": "c523de53-8b8e-47fa-a751-15f0e678f8d9"
}

###
POST http://localhost:8081/users/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "JoJow",
  "password": "strongPassword123",
  "email": "joaovlopes000@gmail.com"
}

###
GET http://localhost:8081/users/bd42b8fd-5ba1-482b-8b3e-13b77095a7d7
Authorization: Bearer {{authToken}}

###
POST http://localhost:8081/users/roles
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "bd42b8fd-5ba1-482b-8b3e-13b77095a7d7",
  "roleId": "5658b58d-b749-4a74-bb71-483324eb0705"
}

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "email": "joaovlopes000@gmail.com",
  "password": "strongPassword123"
}
